CREATE TABLE historic(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
    value_from DECIMAL NOT NULL,
    unity_from VARCHAR NOT NULL,
    value_to DECIMAL NOT NULL,
    unity_to VARCHAR NOT NULL
)